Marcestus/OhTu_miniprojekti

- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
> dao/domain: lukuvinkkiin lisätty id ominaisuus ja dao:ssa metodi kirjattu poistamiseen jotta domain puolella voidaan kutsua oikein

- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
> domain: hashmap ennakkotägejä varten, metodi automaattisille tägeille ja muodostaTagit metodia muutettu aikaisempien perusteella

- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
> Domain/UI: tägeihin perustuva haku toteutettu, lisätty komento käyttö liittymään haulle

- src/main/java/lukuvinkki/domain/Lukuvinkki.java
- src/main/java/lukuvinkki/domain/StubIO.java
ArrayList typesafety lisätty () -> <>()
Lukuvinkille lisätty unohtunut getID metodi tulevaisuutta varten
> Domain/Lukuvinkki: typesafety asioita ArrayListeille, ja lukuvinkille luotu getID()

- src/main/java/lukuvinkki/dao/Tietokantahallinta.java
- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
Osa user story 5:ttä (tietokantaosuus), katselmoitavaksi
> Dao: luo poistaLukuVinkki metodi

- src/test/java/lukuvinkki/domain/LukuvinkkipalveluTest.java
> lisää testejä lukuvinkkipalveluun

- src/main/java/lukuvinkki/domain/Lukuvinkki.java
- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
> Koodiparantelua

- src/test/java/lukuvinkki/dao/TietokantahallintaTest.java
- src/test/java/lukuvinkki/domain/LukuvinkkipalveluTest.java
> Testeja tietokantahallintaan

- build.gradle
- src/test/java/lukuvinkki/dao/TietokantahallintaTest.java
- src/test/java/lukuvinkki/domain/LukuvinkkipalveluTest.java
Poistettu kayttoliittyma.java -tiedosto checkstyleista ja korjattu tänään tehtyjä testejä, jotta täyttävät säännöt
> Checkstyle saannot ja korjaukset

- src/main/java/lukuvinkki/dao/Tietokantahallinta.java
Daon poistometodin pieni fiksaus yhteyden avaukseen ja sulkemiseen
> dao: poisto korjattu, ja samalla testit

- build.gradle
- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
- src/test/java/lukuvinkki/Stepdefs.java
- src/test/java/lukuvinkki/domain/LukuvinkkipalveluTest.java
- src/test/resources/lukuvinkki/lukuvinkinLisays.feature
Otsikko haetaan annetusta URL:sta jos käyttäjä näin haluaa. Muuten käytetään aiemmin syötettyä otsikkoa.
> UI, domain: otsikon haku url-osoitteesta lisätty

- .gitignore
- src/test/java/lukuvinkki/Stepdefs.java
- src/test/resources/lukuvinkki/lukuvinkinLisays.feature
> Testit: korjattu facebook ongelma

- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
- src/test/java/lukuvinkki/Stepdefs.java
- src/test/java/lukuvinkki/domain/LukuvinkkipalveluTest.java
- src/test/resources/lukuvinkki/lukuvinkinLisays.feature
- src/test/resources/lukuvinkki/lukuvinkkienHaku.feature
Url:n normalisointi ja testejä lisätty
> Domain, tests: url normisointia viilattu, testeja lisatty

- src/main/java/lukuvinkki/dao/TietokantaRajapinta.java
- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
> Poista lukuvinkki UI

- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
- src/test/resources/lukuvinkki/lukuvinkinLisays.feature
- src/test/resources/lukuvinkki/lukuvinkinPoisto.feature
> Poiston viilaus kayttoliittymaan

- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
- src/test/java/lukuvinkki/Stepdefs.java
- src/test/resources/lukuvinkki/lukuvinkinPoisto.feature
> Cucumber: cucumber testit poistoon lisatty

- .gitignore
- build.gradle
- src/main/java/lukuvinkki/dao/TietokantaRajapinta.java
- src/main/java/lukuvinkki/dao/Tietokantahallinta.java
- src/main/java/lukuvinkki/domain/Lukuvinkki.java
- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
- src/main/java/lukuvinkki/domain/StubIO.java
- src/main/java/lukuvinkki/paaohjelma/Main.java
- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
- src/test/java/lukuvinkki/Stepdefs.java
- src/test/java/lukuvinkki/dao/TietokantahallintaTest.java
- src/test/java/lukuvinkki/domain/LukuvinkkipalveluTest.java
> Pieniä korjauksia kaikissa pakkauksissa

- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
- src/test/java/lukuvinkki/Stepdefs.java
- src/test/java/lukuvinkki/domain/LukuvinkkipalveluTest.java
- src/test/resources/lukuvinkki/lukuvinkinPoisto.feature
UI:n ja domainin refaktorointia poiston metodien suhteen.
Automaattisten tagien korjaus
> UI/domain: UI:n ja domainin refaktorointi

- src/main/java/lukuvinkki/domain/Tiedostopalvelu.java
- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
Tiedoston tarkastukseen oma luokka
> Domain: tiedoston olemassa olon tarkastus

- src/main/java/lukuvinkki/dao/Tietokantahallinta.java
- src/main/java/lukuvinkki/domain/Lukuvinkki.java
- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
- src/test/java/lukuvinkki/Stepdefs.java
- src/test/java/lukuvinkki/dao/TietokantahallintaTest.java
- src/test/java/lukuvinkki/domain/LukuvinkkiTest.java
- src/test/java/lukuvinkki/domain/LukuvinkkipalveluTest.java
- src/test/java/lukuvinkki/domain/UrlPalveluTest.java
- src/test/resources/lukuvinkki/lukuvinkinLisays.feature
- src/test/resources/lukuvinkki/lukuvinkkienHaku.feature
Testit korjattu, lukuvinkkien listaaminen tehty, pientä refaktorointia,
> Listaa lukuvinkit

- src/main/java/lukuvinkki/dao/TietokantaRajapinta.java
- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
UI:n mahdollisuus lukuvinkin luetuksi merkkaamiselle ja logiikka domainin puolelle tehty
> Domain, UI: lukuvinkille mahdollisuus luetuksi merkkaaminen

- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
- src/test/java/lukuvinkki/domain/LukuvinkkipalveluTest.java
Luetuksi merkkaus vain lukemattomalle vinkille
> Domain,UI: luetuksi merkkaus mahdollista vain lukemattomalla vinkille

- src/main/java/lukuvinkki/ui/Kayttoliittyma.java
- src/test/java/lukuvinkki/Stepdefs.java
- src/test/resources/lukuvinkki/lukuvinkkienExport.feature
Ratkaisuna hieman tunkki, mutta toimii tarkoitukseen
> UI/cucumber: UI ilmoittaa exportin nimen ja lokaation. Cucumber osaa poistaa testi exportin

- src/main/java/lukuvinkki/domain/Lukuvinkkipalvelu.java
- src/test/java/lukuvinkki/domain/LukuvinkkiTest.java
- src/test/java/lukuvinkki/domain/LukuvinkkipalveluTest.java
Domain: lukuvinkkipalvelun lukemattoman lukuvinkin haun metodista siistimpi
> Domain: lukemattoman lukuvinkin hakumetodin refaktorointi
